// bitc-configurator: management of a small set of Linux computers
// Copyright(c) 2014 Joshua Oldenburg (http://joshuaoldenburg.com)
// Released under the GPLv3 license. See LICENSE.txt for more info

var colors = require('colors');
var exec = require('child_process').exec;
var util = require('util');

/*
* Defines the following tasks:
* - bitc:setup:bitc:ssh
* - bitc:setup:bitc:ssh:client
* - bitc:setup:bitc:ssh:server
*/

module.exports = function(grunt) {
	var _conf = grunt.file.readJSON('/etc/bitc/conf.json');
	
	grunt.registerTask('bitc:setup:ssh', [
		_conf.isServer ? 'bitc:setup:ssh:server' : 'bitc:setup:ssh:client',
	]);
	
	grunt.registerTask('bitc:setup:ssh:server', 'set up SSH - server', function() {
		grunt.log.writeln('Generating SSH key...');
		var done = this.async();
		
		exec('ssh-keygen -q -b 2048 -t rsa -N "" -C "BITC global key" -f /etc/bitc/globalKey', {
			timeout: 10000,
		}, function(error, stdout, stderr) {
			if (error) {
				grunt.log.writeln('Error generating SSH key: ' + util.inspect(error)).error();
				done();
			}
			if (!grunt.file.isFile('/etc/bitc/globalKey') || !grunt.file.isFile('/etc/bitc/globalKey.pub')) {
				grunt.log.writeln('SSH key not successfully generated! This should never happen.').error();
				done();
			}
			
			grunt.log.writeln('Successfully generated SSH key.').ok();
			done();
		});
	});
	
	grunt.registerTask('bitc:setup:ssh:client', 'set up SSH - client', function() {
		grunt.log.writeln('FIXME: dummy bitc:setup:ssh task\n'.red).ok();
	});
}

// Command to generate key: ssh-keygen -q -b 2048 -t rsa -N '' -C 'BITC intranet global key generated by bitc-configurator on <date>' -f <output-path>